src/Entity/Delivery_address.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Delivery_address
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="delivery_address")
 */
class Delivery_address
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Settlement
     * @ORM\JoinColumn(name="settlement_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Settlement")
     */
    private $settlement_ID;


    /**
     * @var string|null
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $address;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Settlement
     */
    public function getSettlementID(): Settlement
    {
        return $this->settlement_ID;
    }

    /**
     * @param Settlement $settlement_ID
     */
    public function setSettlementID(Settlement $settlement_ID): void
    {
        $this->settlement_ID = $settlement_ID;
    }

    /**
     * @return string|null
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param string|null $address
     */
    public function setAddress(?string $address): void
    {
        $this->address = $address;
    }
}

src/Entity/Order.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Order
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var User
     * @ORM\JoinColumn(name="user_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="User")
     */
    private $user_ID;

    /**
     * @var Client
     * @ORM\JoinColumn(name="clientID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Client")
     */
    private $clientID;

    /**
     * @var Phone
     * @ORM\JoinColumn(name="phone_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Phone")
     */
    private $phone_ID;

    /**
     * @var Warehouse
     * @ORM\JoinColumn(name="warehouse_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Warehouse")
     */
    private $warehouse_ID;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false)
     */
    private $amount;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false)
     */
    private $price;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $date;

    /**
     * @var string
     * @ORM\Column(type="string", length=30, nullable=false)
     */
    private $orderNumber;


    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getUserID(): User
    {
        return $this->user_ID;
    }

    /**
     * @param User $user_ID
     */
    public function setUserID(User $user_ID): void
    {
        $this->user_ID = $user_ID;
    }

    /**
     * @return Client
     */
    public function getClientID(): Client
    {
        return $this->clientID;
    }

    /**
     * @param Client $clientID
     */
    public function setClientID(Client $clientID): void
    {
        $this->clientID = $clientID;
    }

    /**
     * @return Phone
     */
    public function getPhoneID(): Phone
    {
        return $this->phone_ID;
    }

    /**
     * @param Phone $phone_ID
     */
    public function setPhoneID(Phone $phone_ID): void
    {
        $this->phone_ID = $phone_ID;
    }

    /**
     * @return Warehouse
     */
    public function getWarehouseID(): Warehouse
    {
        return $this->warehouse_ID;
    }

    /**
     * @param Warehouse $warehouse_ID
     */
    public function setWarehouseID(Warehouse $warehouse_ID): void
    {
        $this->warehouse_ID = $warehouse_ID;
    }

    /**
     * @return int
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * @param int $amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * @return int
     */
    public function getPrice(): int
    {
        return $this->price;
    }

    /**
     * @param int $price
     */
    public function setPrice(int $price): void
    {
        $this->price = $price;
    }

    /**
     * @return \DateTime
     */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date
     */
    public function setDate(\DateTime $date): void
    {
        $this->date = $date;
    }

    /**
     * @return string
     */
    public function getOrderNumber(): string
    {
        return $this->orderNumber;
    }

    /**
     * @param string $orderNumber
     */
    public function setOrderNumber(string $orderNumber): void
    {
        $this->orderNumber = $orderNumber;
    }
}

src/Entity/Region.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Region
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="region")
 */
class Region implements \JsonSerializable
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $region_name;

    /**
     * @var Country
     * @ORM\JoinColumn(name="country_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Country")
     */
    private $country_ID;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getRegionName(): string
    {
        return $this->region_name;
    }

    /**
     * @param string $region_name
     */
    public function setRegionName(string $region_name): void
    {
        $this->region_name = $region_name;
    }

    /**
     * @return Country
     */
    public function getCountryID(): Country
    {
        return $this->country_ID;
    }

    /**
     * @param Country $country_ID
     */
    public function setCountryID(Country $country_ID): void
    {
        $this->country_ID = $country_ID;
    }

    public function jsonSerialize()
    {
        return ["id" => $this->id, "country_ID" => $this->country_ID, "region_name" => $this->region_name];
    }
}

src/Entity/Settlement.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Settlement
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="settlement")
 */
class Settlement implements \JsonSerializable
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Region
     * @ORM\JoinColumn(name="region_ID", referencedColumnName="id")
     * @ORM\ManyToOne(targetEntity="Region")
     */
    private $region_ID;

    /**
     * @var string
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $settlementName;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false)
     */
    private $postalCode;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Region
     */
    public function getRegionID(): Region
    {
        return $this->region_ID;
    }

    /**
     * @param Region $region_ID
     */
    public function setRegionID(Region $region_ID): void
    {
        $this->region_ID = $region_ID;
    }

    /**
     * @return string
     */
    public function getSettlementName(): string
    {
        return $this->settlementName;
    }

    /**
     * @param string $settlementName
     */
    public function setSettlementName(string $settlementName): void
    {
        $this->settlementName = $settlementName;
    }

    /**
     * @return int
     */
    public function getPostalCode(): int
    {
        return $this->postalCode;
    }

    /**
     * @param int $postalCode
     */
    public function setPostalCode(int $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    public function jsonSerialize()
    {
        return ["id" =>$this->id,"region_ID" => $this->region_ID, "settlementName" =>$this->settlementName, "postalCode" => $this->postalCode];
    }
}

src/Controller/StockController.php
<?php


namespace App\Controller;

use App\Entity\User;
use App\Model\Interfaces\StockModelInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StockController extends AbstractController
{
    /** @var StockModelInterface */
    private $stockModel;

    /**
     * StockController constructor.
     * @param StockModelInterface $stockModel
     */
    public function __construct(StockModelInterface $stockModel)
    {
        $this->stockModel = $stockModel;
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="addStock", path="/addStock")
     */
    public function addStock(Request $request):Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        /** @var User $user */
        $user = $this->getUser();
        if($request->isMethod("POST")){
            if($this->stockModel->addStock($request, $user)=== true){
                return $this->render("Stock/orderedStock.html.twig",[
                    "stocks" => $this->stockModel->allOrderedStock(),
                    "user" => $this->getUser(),
                    "resultMessage"=> "Sikeres hozzáadás!",
                    "resultColor" => "success"
                ]);
            }
            return $this->render("Stock/orderedStock.html.twig",[
                "stocks" => $this->stockModel->allOrderedStock(),
                "user" => $this->getUser(),
                "resultMessage"=> "Sikertelen hozzáadás!",
                "resultColor" => "danger"
            ]);
        }
        return $this->redirectToRoute('orderedStock');
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="orderedStock", path="/orderedStock")
     */
    public function orderedStock(Request $request):Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        return $this->render("Stock/orderedStock.html.twig",[
            "stocks" => $this->stockModel->allOrderedStock(),
            "user" => $this->getUser(),
            "resultMessage"=> "",
            "resultColor" => ""
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="allStock", path="/allStock")
     */
    public function allStock(Request $request):Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        return $this->render("Stock/allStock.html.twig",[
            "stocks" => $this->stockModel->allArrivedStock(),
            "user" => $this->getUser(),
            "resultMessage"=> "",
            "resultColor" => "",
            "allElement" => ""
        ]);
    }
    /**
     * @param Request $request
     * @param int $stockId
     * @return Response
     * @Route(name="updateOrderedStock", path="/updateOrdered/{stockId}")
     */
    public function updateOrdered(Request $request, int $stockId): Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        if($request->isMethod("POST")){
            if($this->stockModel->edit($request, $stockId,$this->getUser()) === true){
                return $this->render("Stock/orderedStock.html.twig",[
                    "stocks" => $this->stockModel->allOrderedStock(),
                    "user" => $this->getUser(),
                    "resultMessage"=> "Sikeres módosítás!",
                    "resultColor" => "success", "allElement" => ""
                ]);
            }else return $this->render("Stock/orderedStock.html.twig",[
                "stocks" => $this->stockModel->allOrderedStock(),
                "user" => $this->getUser(),
                "resultMessage"=> "Sikertelen módosítás!",
                "resultColor" => "danger", "allElement" =>""
            ]);
        }
        return $this->render("Stock/orderedStock.html.twig",["stocks" => $this->stockModel->allOrderedStock(),
            "user" => $this->getUser(),
            "resultMessage"=> "",
            "resultColor" => "",
            "allElement" => ""
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="sellingStock", path="/sellingStock")
     */
    public function sellingStock(Request $request):Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        /** @var User $user */
        $user = $this->getUser();
        if($request->isMethod("POST")){
            return $this->render("Stock/bill.html.twig", [
                "orderedPhones" => $this->stockModel->sellStock($request, $user),
                "user" =>$this->getUser()
            ]);
        }
        return $this->render("Stock/sellingStock.html.twig", [
            "stocks" => $this->stockModel->allArrivedStock(),
            "user" => $this->getUser(), "result" =>"",
            "wh" => $this->stockModel->warehouseById()
        ]);
    }

    /**
     * @return Response
     * @Route(name="allWarehouse", path="/allWarehouse")
     */
    public function allWarehouse():Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        return new JsonResponse($this->stockModel->allWarehouse());
    }

    /**
     * @return Response
     * @Route(name="allStatus", path="/allStatus")
     */
    public function allStatus():Response{
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $status = $this->stockModel->allStatus();
        return new JsonResponse($status);
    }

    /**
     * @param Request $request
     * @Route(name="billPDF", path="/billPDF")
     */
    public function generateBillPDF(Request $request){
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $html = $this->renderView('Stock/billPDF.html.twig', [
            "orderedPhones" => $this->stockModel->lastSell(),
            "user" =>$this->getUser()]);
        $this->stockModel->billPDF($html);
    }

    /**
     * @Route(name="generateOrderedPDF", path="/generateOrderedPDF")
     */
    public function generateOrderedPDF(){
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $html = $this->renderView('Stock/orderedStockPDF.html.twig', ["stocks" => $this->stockModel->allOrderedStock()]);
        $this->stockModel->OrderedPDF($html);
    }

    /**
     * @Route(name="generateOrderedExcel", path="/generateOrderedExcel")
     */
    public function generateOrderedExcel(){
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $this->stockModel->OrderedExcel();
    }

    /**
     * @Route(name="generateArrivedPDF", path="/generateArrivedPDF")
     */
    public function generateArrivedPDF(){
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $html = $this->renderView('Stock/arrivedStockPDF.html.twig', ["stocks" => $this->stockModel->allArrivedStock()]);
        $this->stockModel->ArrivedPDF($html);
    }

    /**
     * @Route(name="generateArrivedExcel", path="/generateArrivedExcel")
     */
    public function generateArrivedExcel(){
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        $this->stockModel->ArrivedExcel();
    }


}

templates/Stock/arrivedStockPDF.html.twig
{% extends 'base.html.twig' %}
{# @var stocks \App\Entity\Stock[] #}

{% block title %}
    Készlet - PDF
{% endblock %}

{% block body %}
    <h1 style="margin-bottom: 5px; text-align: center;">Beérkezett telefonok adatai</h1><br>
    <div>
        <table border="1" style="margin: auto;">
            <thead>
            <tr>
                <th>Mennyiség</th>
                <th>Beszerzési ár</th>
                <th>Telefon</th>
                <th>Raktár</th>
                <th>Státusz</th>
                <th>Dátum</th>
                <th>Felhasználó</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr>
                    <td>{{ stock.amount }}</td>
                    <td>{{ stock.purchasePrice }}</td>
                    <td>
                        <span>{{ stock.phoneID.brandID.brandName }} </span>
                        <span>{{ stock.phoneID.modelID.modelName }} </span>
                        <span>{{ stock.phoneID.colorID.phoneColor }} </span>
                        <span>{{ stock.phoneID.capacityID.capacity }} GB </span>
                    </td>
                    <td>{{ stock.warehouseID.whName }}</td>
                    <td>{{ stock.statusID.status }}</td>
                    <td>{{ stock.date|date('Y-m-d H:i:s') }}</td>
                    <td>{{ stock.userID.username }} ({{ stock.userID.roles[0] }})</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr></tr>
            </tfoot>
        </table>
    </div>
{% endblock %}

templates/Stock/bill.html.twig
{% extends 'index.html.twig' %}
{# @var orderedPhones \App\Entity\Order[] #}

{% block content %}
    {% set whName = "" %}
    {% set address = "" %}
    {% set vatNumber = "" %}
    {% set client = "" %}
    {% set clientCountry = "" %}
    {% set clientRegion = "" %}
    {% set clientPostal = "" %}
    {% set clientSettlement = "" %}
    {% set clientAddress = "" %}
    {% set clientVat = "" %}
    {% set orderNumber = "" %}
    {% for data in orderedPhones %}
        {% set whName = data.warehouseID.whName %}
        {% set address = data.warehouseID.location %}
        {% set vatNumber = data.warehouseID.vatNumber %}
        {% set client = data.clientID.clientName %}
        {% set clientCountry = data.clientID.deliveryID.settlementID.regionID.countryID.countryName %}
        {% set clientRegion = data.clientID.deliveryID.settlementID.regionID.regionName %}
        {% set clientPostal = data.clientID.deliveryID.settlementID.postalCode %}
        {% set clientSettlement = data.clientID.deliveryID.settlementID.settlementName %}
        {% set clientAddress = data.clientID.deliveryID.address %}
        {% set clientVat = data.clientID.vatNumber %}
        {% set orderNumber = data.orderNumber %}
    {% endfor %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col">
                <a href="{{ path('billPDF') }}" class="btn btn-primary buttonDesign" style="border-radius: 0;" type="button">PDF</a>
                <a href="{{ path('main') }}" class="btn btn-primary buttonDesign" style="border-radius: 0;" type="button">Tovább a főoldalra</a>
            </div>
        </div>
        <div class="bg-light" style="border-style: solid;width: 100% !important;margin-bottom:20px;">
            <div class="row" style="margin:auto;padding-top: 20px;">
                <div class="col d-flex justify-content-start">
                    <h1 class="text-uppercase text-center" style="padding-bottom: 40px;">Számla</h1>
                </div>
                <div class="col">
                    <p class="text-end" style="margin-bottom: 1px;">Rendelési azonosító:</p>
                    <p class="fw-bold text-end"><span style="padding-right:1.6rem;">{{ orderNumber }}</span></p>
                </div>
            </div>
            <div class="row" style="margin:auto;background: rgba(177,233,254,0.6);">
                <div class="col d-flex align-items-center">
                    <h6>Számla kiállító adatai:<br></h6>
                </div>
                <div class="col d-flex align-items-center">
                    <h6>Vevő adatai:<br></h6>
                </div>
            </div>
            <div class="row" style="margin:auto;">
                <div class="col">
                    <p class="fw-bold" style="margin-bottom: 0 !important;">{{ whName }}</p>
                    <p style="margin-bottom: 0 !important;">Cím: {{ address }}</p>
                    <p>Adószám: {{ vatNumber }}</p>
                </div>
                <div class="col">
                    <p class="fw-bold" style="margin-bottom: 0 !important;">{{ client }}</p>
                    <p style="margin-bottom: 0 !important;">Cím: {{ clientPostal }} {{ clientSettlement }}, {{ clientAddress }}</p>
                    <p>Adószám:&nbsp;{{ clientVat }}</p>
                </div>
            </div>
            <div class="row" style="margin:auto;background: rgba(177,233,254,0.6);">
                <div class="col d-flex align-items-center">
                    Szállítási cím
                </div>
            </div>
            <div class="row" style="margin:auto;">
                <div class="col d-flex align-items-center">
                    <span>{{ clientCountry|upper }}, </span> {{ clientRegion }}, {{ clientPostal }} {{ clientSettlement }}, {{ clientAddress }}
                </div>
            </div>
            <div class="row" style="margin:auto;background: rgba(177,233,254,0.6);">
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>Fizetési mód<br></h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>Számla kelte</h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>Teljesítés időpontja<br></h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>Fizetési határidő</h6>
                </div>
            </div>
            {% set datetime = date('')|date("Y/m/d") %}
            <div class="row" style="margin:auto;background: rgba(249,12,12,0);">
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>Átutalás</h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>{{ datetime }}</h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>{{ datetime }}<br></h6>
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <h6>{{ datetime|date_modify('+1 day')|date("Y/m/d")}}<br></h6>
                </div>
            </div>

            <div class="row" style="margin:auto;background: rgba(177,233,254,0);">
                <table>
                    {% set fullPrice = 0 %}
                    <tr style="text-align: center !important;background: rgba(177,233,254,0.6);">
                        <th>Termék</th>
                        <th>Mennyiség</th>
                        <th>Nettó egységár</th>
                        <th>ÁFA</th>
                        <th>Nettó</th>
                    </tr>
                    {% for data in orderedPhones %}
                        <tr style="text-align: center !important;border-bottom:1px solid gainsboro;" >
                            <td>{{ data.phoneID.brandID.brandName }}
                                {{ data.phoneID.modelID.modelName }}
                                {{ data.phoneID.colorID.phoneColor }}
                                {{ data.phoneID.capacityID.capacity }} GB
                            </td>
                            <td>{{ data.amount }}</td>
                            <td>{{ data.price|number_format(0,","," ") }} Ft</td>
                            <td>0%</td>
                        {% set deviceFullPrice = data.price * data.amount %}
                            <td>{{ deviceFullPrice|number_format(0,","," ") }} Ft</td>
                        </tr>
                        {% set fullPrice = fullPrice + deviceFullPrice %}
                    {% endfor %}
                </table>
            </div>
            <div class="row" style="margin:auto;background: rgba(177,233,254,0.6);">
                <div class="col offset-md-0 d-flex justify-content-end align-items-center">
                    <h5 class="fw-bold">Nettó összeg</h5>
                </div>
            </div>
            <div class="row" style="margin:auto;">
                <div class="col d-flex justify-content-end align-items-center">
                    <p>{{ fullPrice|number_format(0,","," ") }} Ft</p>
                </div>
            </div>
            <div class="row" style="margin:auto;">
                <div class="col d-flex justify-content-end align-items-center">
                    <p>+0% ÁFA: 0 Ft</p>
                </div>
            </div>
            <div class="row" style="margin:auto;">
                <div class="col d-flex justify-content-end align-items-center">
                    <p>Végösszeg: {{ fullPrice|number_format(0,","," ") }} Ft</p>
                </div>
            </div>

            <div class="row" style="margin:auto;background: rgba(249,12,12,0);">
                <div class="col d-flex justify-content-center align-items-center">
                    <h4 class="w-100" style="margin-top: 20px;">Köszönjük a vásárlást!</h4>
                </div>
            </div>
            <div class="row" style="margin:auto;background: rgba(249,12,12,0);">
                <div class="col d-flex justify-content-end align-items-center">
                    <h1 class="w-100" style="margin-top: 50px;text-align: right;">IStorage</h1>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Stock/orderedStockPDF.html.twig
{% extends 'base.html.twig' %}
{# @var stocks \App\Entity\Stock[] #}

{% block title %}
    Készlet - PDF
{% endblock %}

{% block body %}
    <h1 style="margin-bottom: 5px; text-align: center;">Megrendelt telefonok adatai</h1><br>
    <div>
        <table border="1" style="margin: auto;">
            <thead>
            <tr>
                <th>Mennyiség</th>
                <th>Beszerzési ár</th>
                <th>Telefon</th>
                <th>Raktár</th>
                <th>Státusz</th>
                <th>Dátum</th>
                <th>Felhasználó</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr>
                    <td>{{ stock.amount }}</td>
                    <td>{{ stock.purchasePrice }}</td>
                    <td>
                        <span>{{ stock.phoneID.brandID.brandName }} </span>
                        <span>{{ stock.phoneID.modelID.modelName }} </span>
                        <span>{{ stock.phoneID.colorID.phoneColor }} </span>
                        <span>{{ stock.phoneID.capacityID.capacity }} GB </span>
                    </td>
                    <td>{{ stock.warehouseID.whName }}</td>
                    <td>{{ stock.statusID.status }}</td>
                    <td>{{ stock.date|date('Y-m-d H:i:s') }}</td>
                    <td>{{ stock.userID.username }} ({{ stock.userID.roles[0] }})</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr></tr>
            </tfoot>
        </table>
    </div>
{% endblock %}